# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Exaile 
tagline:          Music Player for GTK+
url:              http://exaile-dev.github.io
paginate:         5
baseurl:          /
author:
  name:           Exaile Developer Team
  url:            http://www.exaile.org
  email:          exaile-devel@googlegroups.com

# Menu setup
menu:
    - ["Home", "/"]
    - ["Download", "/download/"]
    - ["Screenshots", "/screens/"]
    - ["Support", "/support"]
    - ["Documentation", "http://exaile.readthedocs.org"]
    - ["Bug Tracker", "https://github.com/exaile-dev/exaile/issues"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/exaile-dev/exaile-dev.github.io
