# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Exaile 
tagline:          Music Player for GTK+
url:              http://exaile-dev.github.io
paginate:         5
baseurl:          /
author:
  name:           Exaile Developer Team
  url:            http://www.exaile.org
  email:          exaile-devel@googlegroups.com

# Menu setup
menu:
    - ["Get It", "/download/"]
    - ["Screenshots", "/screens/"]
    - ["Docs", "http://exaile.readthedocs.org"]
    - ["Support", "/support"]
    - ["Code", "https://github.com/exaile-dev/exaile"]
    - ["Bugs", "https://github.com/exaile-dev/exaile/issues"]

# Exaile versions, used in various places
exaile:
  version:        3.4.1
  srcver:         3.4.1
  osxver:         3.4.1
  winver:         3.4.1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/exaile-dev/exaile-dev.github.io
